basePath: /
definitions:
  github_com_sd0hni-psina_happytail_internal_models.Adoption:
    properties:
      animal_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  github_com_sd0hni-psina_happytail_internal_models.Animal:
    properties:
      age:
        type: integer
      breed:
        type: string
      color:
        type: string
      created_at:
        type: string
      description:
        type: string
      has_vet_passport:
        type: boolean
      id:
        type: integer
      is_vaccinated:
        type: boolean
      name:
        type: string
      share_count:
        type: integer
      shelter_id:
        type: integer
      status:
        type: string
      type:
        $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.AnimalType'
    type: object
  github_com_sd0hni-psina_happytail_internal_models.AnimalPhoto:
    properties:
      animal_id:
        type: integer
      created_at:
        type: string
      id:
        type: integer
      is_main:
        type: boolean
      url:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.AnimalPhotoInput:
    properties:
      animal_id:
        type: integer
      is_main:
        type: boolean
      url:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.AnimalType:
    enum:
    - dog
    - cat
    - bunny
    type: string
    x-enum-varnames:
    - AnimalTypeDog
    - AnimalTypeCat
    - AnimalTypeBunny
  github_com_sd0hni-psina_happytail_internal_models.AuthResponse:
    properties:
      token:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.CreateAdoptionInput:
    properties:
      animal_id:
        type: integer
    type: object
  github_com_sd0hni-psina_happytail_internal_models.CreateAnimalInput:
    properties:
      age:
        type: integer
      animal_type:
        $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.AnimalType'
      breed:
        type: string
      color:
        type: string
      description:
        type: string
      has_vet_passport:
        type: boolean
      is_vaccinated:
        type: boolean
      name:
        type: string
      shelter_id:
        type: integer
    type: object
  github_com_sd0hni-psina_happytail_internal_models.CreatePostInput:
    properties:
      animalID:
        type: integer
      contactInfo:
        type: string
      listingType:
        $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.ListingType'
      photoURLs:
        items:
          type: string
        type: array
      price:
        $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Money'
      reason:
        type: string
      userID:
        type: integer
    type: object
  github_com_sd0hni-psina_happytail_internal_models.CreateShelterInput:
    properties:
      address:
        type: string
      email:
        type: string
      name:
        type: string
      phone_number:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.CreateUserInput:
    properties:
      city:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.ListingType:
    enum:
    - sale
    - give
    type: string
    x-enum-varnames:
    - ListingTypeSale
    - ListingTypeGive
  github_com_sd0hni-psina_happytail_internal_models.LoginInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.Money:
    properties:
      amount:
        type: integer
      currency:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.Post:
    properties:
      animal_id:
        type: integer
      contact_info:
        type: string
      created_at:
        type: string
      id:
        type: integer
      listing_type:
        $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.ListingType'
      photo_urls:
        items:
          type: string
        type: array
      price:
        $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Money'
      reason:
        type: string
      status:
        $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.PostStatus'
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  github_com_sd0hni-psina_happytail_internal_models.PostStatus:
    enum:
    - active
    - inactive
    - deleted
    type: string
    x-enum-varnames:
    - PostStatusActive
    - PostStatusInactive
    - PostStatusDeleted
  github_com_sd0hni-psina_happytail_internal_models.Shelter:
    properties:
      address:
        type: string
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone_number:
        type: string
    type: object
  github_com_sd0hni-psina_happytail_internal_models.User:
    properties:
      city:
        type: string
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      phone_number:
        type: string
      points:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: Backend API для платформы по усыновлению домашних животных.
  title: Happytail API
  version: "1.0"
paths:
  /adoptions:
    post:
      consumes:
      - application/json
      parameters:
      - description: данные заявки
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.CreateAdoptionInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Adoption'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Создать заявку на усыновление
      tags:
      - adoptions
  /animals:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Animal'
            type: array
      summary: Получить всех животных
      tags:
      - animals
    post:
      consumes:
      - application/json
      parameters:
      - description: данные животного
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.CreateAnimalInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Animal'
      security:
      - ApiKeyAuth: []
      summary: Создать животное
      tags:
      - animals
  /animals/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID животного
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Animal'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить животное по ID
      tags:
      - animals
  /animals/{id}/photos:
    get:
      description: Возвращает список фото для конкретного животного (главное фото
        первым)
      parameters:
      - description: ID животного
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.AnimalPhoto'
            type: array
        "400":
          description: Invalid id
          schema:
            type: string
        "404":
          description: Not found
          schema:
            type: string
        "500":
          description: Failed to fetch photos
          schema:
            type: string
      summary: Получить все фото животного
      tags:
      - AnimalPhotos
    post:
      consumes:
      - application/json
      description: Добавляет новое фото для конкретного животного
      parameters:
      - description: ID животного
        in: path
        name: id
        required: true
        type: integer
      - description: данные фото
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.AnimalPhotoInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.AnimalPhoto'
        "400":
          description: Invalid input
          schema:
            type: string
        "500":
          description: Failed to add photo
          schema:
            type: string
      summary: Добавить фото животного
      tags:
      - AnimalPhotos
  /animals/{id}/photos/{photo_id}/main:
    patch:
      description: Устанавливает фото как главное для животного
      parameters:
      - description: ID животного
        in: path
        name: id
        required: true
        type: integer
      - description: ID фото
        in: path
        name: photo_id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid id
          schema:
            type: string
        "404":
          description: Photo not available
          schema:
            type: string
        "500":
          description: Internal error
          schema:
            type: string
      summary: Сделать фото главным
      tags:
      - AnimalPhotos
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: логин и пароль
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.AuthResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Логин пользователя
      tags:
      - auth
  /photos/{photo_id}:
    delete:
      description: Удаляет фото по ID
      parameters:
      - description: ID фото
        in: path
        name: photo_id
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Invalid id
          schema:
            type: string
        "500":
          description: Failed to delete photo
          schema:
            type: string
      summary: Удалить фото
      tags:
      - AnimalPhotos
  /post:
    post:
      consumes:
      - application/json
      description: Создаёт новый пост
      parameters:
      - description: данные поста
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.CreatePostInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Post'
        "400":
          description: Invalid input
          schema:
            type: string
        "409":
          description: Conflict
          schema:
            type: string
        "500":
          description: Failed to create post
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Создать пост
      tags:
      - Post
  /post/{id}:
    get:
      description: Возвращает один пост по его ID
      parameters:
      - description: ID поста
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Post'
        "400":
          description: Invalid post ID
          schema:
            type: string
        "404":
          description: Post not found
          schema:
            type: string
        "500":
          description: Failed to fetch post
          schema:
            type: string
      summary: Получить пост по ID
      tags:
      - Post
  /posts:
    get:
      description: Возвращает список всех постов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Post'
            type: array
        "500":
          description: Failed to fetch posts
          schema:
            type: string
      summary: Получить все посты
      tags:
      - Post
  /shelters:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Shelter'
            type: array
      summary: Получить все приюты
      tags:
      - shelters
    post:
      consumes:
      - application/json
      parameters:
      - description: данные приюта
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.CreateShelterInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Shelter'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      security:
      - ApiKeyAuth: []
      summary: Создать приют
      tags:
      - shelters
  /shelters/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID приюта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.Shelter'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить приют по ID
      tags:
      - shelters
  /users:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.User'
            type: array
      summary: Получить всех пользователей
      tags:
      - users
    post:
      consumes:
      - application/json
      parameters:
      - description: данные пользователя
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Создать пользователя
      tags:
      - users
  /users/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_sd0hni-psina_happytail_internal_models.User'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить пользователя по ID
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
